services:
  python-app:
    build: .
    container_name: funny-names
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    command: python3 src/main.py
    env_file:
      - .env
